# ========================
# Order Service Configuration
# ========================

# Server
server.port=8081

# H2 Database
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Kafka Producer
# ========================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Kafka Consumer (for SAGA — consuming inventory-events)
spring.kafka.consumer.group-id=order-saga-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.kiran.common.dto.InventoryEvent

# Topic Name
app.kafka.topic=orders-v2

# ========================
# Resilience4j Circuit Breaker
# ========================
spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventory-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventory-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventory-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventory-service.automatic-transition-from-open-to-half-open-enabled=true

# Retry
resilience4j.retry.instances.inventory-service.max-attempts=3
resilience4j.retry.instances.inventory-service.wait-duration=1s

# Actuator (override shared — add circuitbreakers)
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.health.circuitbreakers.enabled=true
