# Application Name
spring.application.name=notification-service

# Server Port
server.port=8082

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer Group
spring.kafka.consumer.group-id=notification-group

# Start reading only new messages
spring.kafka.consumer.auto-offset-reset=latest

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust Packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Convert JSON to InventoryEvent
spring.kafka.consumer.properties.spring.json.value.default.type=com.kiran.common.dto.InventoryEvent

# Topic Name
app.kafka.topic=inventory-events